name: Push Build
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build and Release
    # This job runs on Linux
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_SHA: ${{ github.sha }}
    steps:
      - uses: actions/checkout@v2
      - name: Build the image
        run: docker build -t docker.pkg.github.com/jrtapsell/metabaseautocovid/automatic:$GITHUB_SHA ./
      - name: Login to GitHub Packages
        run: docker login docker.pkg.github.com -u jrtapsell -p "$GITHUB_TOKEN"
      - name: Push the image
        run: docker push docker.pkg.github.com/jrtapsell/metabaseautocovid/automatic:$GITHUB_SHA