name: Greet Everyone
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    name: Build and Release
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the image
        run: docker build -t docker.pkg.github.com/jrtapsell/metabaseautocovid/automatic:latest ./